### ISSUE TITLE
Need more documentation

### ISSUE THREAD

**Issue by FullyArticulate** [awrichar/gradle-external-build#1]
A more complete example would help here. I'm still unable to figure out how this plugs into my broader build.

    apply plugin: 'com.cisco.external-build'
    model { 
        components { 
            mylib(ExternalNativeLibrarySpec) { 
                buildConfig(CMake) { ... }
                buildOutput { ... }
            }
        }
    }

    apply plugin: 'java'
    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
    }

if I run gradle assemble, it does not attempt to build my JNI library at all. Any hints would be greatly appreciated! Thanks!

**Comment by awrichar** [comment]
I agree; I'll try to add some real examples soon. It's possible you need to apply the `c` or `cpp` plugin first to wire up basic tasks for the native build - I have not yet tested in a pure Java/JNI context.

**Comment by awrichar** [comment]
Finally added one full example for CMake - also fixed a few minor bugs along the way. I'll try to add examples for other tools as well, but at least one real-world example is better than none.

**Comment by Quanalogy** [comment]
An explaination of how to change the default compiler would be nice as well. I'm on Fedora and here qmake is called qmake-qt5. You could make a dynamic link to it, but that seems quite pointless to me. 
`environment = ['PATH': '/usr/bin/qmake-qt5',]` makes no difference. (maybe I understand this the wrong way? )

edit: yes i was wrong: code says qmakeExecuteable '/usr/bin/qmake-qt5' for those who'll be needing this.
